public class Address {
    public void homeAddress() {
        String name ='Meruyert';
        System.debug('My name is  '+ name);
        Integer numFamily = 3;
        system.debug('Total number of family is  '+ numFamily);
       String houseName = 'Himels';
       system.debug('House name is  '+ houseName);
        Integer houseNumber = 2415;
        system.debug('House number is  '+houseNumber);
        String streetName = 'Wyckchester Dr';
        system.debug('Street name is  '+ streetName);
       String cityName = 'Pearland';
       system.debug('City name is  ' +cityName);
       String stateName = 'Texas';
       system.debug('State name is  '+ stateName);
        String ISOcode = 'TX77584';
        system.debug('ISO code is  ' + ISOcode);
        String countryName = 'US';
        system.debug('Country name is  '+ countryName);
        String countryISOcode = 'US77584';
        system.debug('Country ISO code is ' + countryISOcode);
        String zipCode = '77584';
        system.debug('Zip code is  '+ zipCode);
       Boolean currentHome = true;
       system.debug('Is this my current address?' + currentHome);
        }
    }

